"""change to moon model

Revision ID: 8e5eff08c92d
Revises: 5b343d48270f
Create Date: 2024-11-05 13:47:37.962102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5eff08c92d'
down_revision = '5b343d48270f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('distance_from_planet')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moon_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'moon', ['moon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('moon_id')

    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_from_planet', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
